from toontown.base import TTLocalizer
UNLOCKED = 0
SUIT_APPROACHING = 1
BUILDING_TAKEOVER = 2
SB_DISGUISE_INCOMPLETE = 3
CB_DISGUISE_INCOMPLETE = 4
LB_DISGUISE_INCOMPLETE = 5
BB_DISGUISE_INCOMPLETE = 6
reasonDict = {UNLOCKED: TTLocalizer.FADoorCodes_UNLOCKED,
 SUIT_APPROACHING: TTLocalizer.FADoorCodes_SUIT_APPROACHING,
 BUILDING_TAKEOVER: TTLocalizer.FADoorCodes_BUILDING_TAKEOVER,
 SB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_SB_DISGUISE_INCOMPLETE,
 CB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_CB_DISGUISE_INCOMPLETE,
 LB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_LB_DISGUISE_INCOMPLETE,
 BB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_BB_DISGUISE_INCOMPLETE}
